### ISSUE TITLE
CLI exit fails if eLink unplugged

### ISSUE THREAD

**Issue by elpollouk** [elpollouk/Itokawa#1]
1. Start CLI with eLink plugged in
2. Unplug eLink
3. Execute `exit` command

Following callstack reported:
```
dcc> exit
Error: Port is not open
    at SerialPort.close (C:\Projects\Itokawa\node_modules\@serialport\stream\lib\index.js:426:29)
    at C:\Projects\Itokawa\dist\devices\asyncSerialPort.js:87:24
    at new Promise (<anonymous>)
    at AsyncSerialPort.close (C:\Projects\Itokawa\dist\devices\asyncSerialPort.js:86:16)
    at ELinkCommandStation.<anonymous> (C:\Projects\Itokawa\dist\devices\commandStations\elink.js:103:30)
    at Generator.next (<anonymous>)
    at C:\Projects\Itokawa\dist\devices\commandStations\elink.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Projects\Itokawa\dist\devices\commandStations\elink.js:4:12)
    at ELinkCommandStation.close (C:\Projects\Itokawa\dist\devices\commandStations\elink.js:99:16)
dcc> exit
TypeError: Cannot read property 'close' of null
    at C:\Projects\Itokawa\dist\devices\asyncSerialPort.js:87:24
    at new Promise (<anonymous>)
    at AsyncSerialPort.close (C:\Projects\Itokawa\dist\devices\asyncSerialPort.js:86:16)
    at ELinkCommandStation.<anonymous> (C:\Projects\Itokawa\dist\devices\commandStations\elink.js:103:30)
    at Generator.next (<anonymous>)
    at C:\Projects\Itokawa\dist\devices\commandStations\elink.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Projects\Itokawa\dist\devices\commandStations\elink.js:4:12)
    at ELinkCommandStation.close (C:\Projects\Itokawa\dist\devices\commandStations\elink.js:99:16)
    at C:\Projects\Itokawa\dist\cli\main.js:53:31
dcc>
```
Exit command doesn't work

**Comment by elpollouk** [comment]
Fixed with commit 2f9498cfe3ce1e8532697657fd104eeecfbefa67
