### ISSUE TITLE
Unrecognised INFO response

### ISSUE THREAD

**Issue by elpollouk** [elpollouk/Itokawa#2]
```
CommandStationError: Unrecognised INFO_RESPONSE, got 62 22 c1 81
    at ELinkCommandStation.<anonymous> (/mnt/data/projects/Itokawa/dist/devices/commandStations/elink.js:233:23)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/data/projects/Itokawa/dist/devices/commandStations/elink.js:5:58)
```

**Comment by elpollouk** [comment]
Debug dump of the error:
```
2020-04-28T13:13:22.187Z: Sent: 21 24 05
2020-04-28T13:13:22.190Z: Recv: 62 22 40 00
2020-04-28T13:13:27.192Z: Sent: 21 24 05
2020-04-28T13:13:27.194Z: Recv: 62 22 40 00
2020-04-28T13:13:32.199Z: Sent: 21 24 05
2020-04-28T13:13:32.202Z: Recv: 62 22 40 00
2020-04-28T13:13:32.842Z: Recv: 61 00 61
2020-04-28T13:13:32.843Z: Recv: 61 00 61
2020-04-28T13:13:32.844Z: Recv: 61 00 61
2020-04-28T13:13:37.207Z: Sent: 21 24 05
```

**Comment by elpollouk** [comment]
More complete dump:
```
2020-04-28T13:23:31.140Z: Recv: 62 22 40 00
2020-04-28T13:23:35.557Z: Recv: 61 00 61
2020-04-28T13:23:35.558Z: Recv: 61 00 61
2020-04-28T13:23:35.559Z: Recv: 61 00 61
2020-04-28T13:23:36.142Z: Sent: 21 24 05
2020-04-28T13:23:36.164Z: Recv: 62 22 c1 81
2020-04-28T13:23:51.173Z: Close: /dev/ttyACM0
2020-04-28T13:23:51.473Z: Open: /dev/ttyACM0
2020-04-28T13:23:51.474Z: Sent: 21 24 05
2020-04-28T13:23:51.476Z: Recv: 62 22 c1 81
```

**Comment by elpollouk** [comment]
Confirmed to be indicating a short circuit. The "clear error" message appears to be [0x21, 0x81, 0xa0] which should be acknowledged with [0x62, 0x22, 0x40] if there is no longer a short.
